### ISSUE TITLE
gpu_ids:1

### ISSUE THREAD

**Issue by stonessss** [jfzhang95/pytorch-deeplab-xception#104]
Why can't I use GPU1 training alone?

**Comment by xysaber** [comment]
same issue

**Comment by xysaber** [comment]
> Why can't I use GPU1 training alone?

how to solve this problem?

**Comment by Qirui-Y** [comment]
Try running the terminal:: CUDA_VISIBLE._DEVICES=1 python train.py --gpu-ids 0 .

**Comment by xysaber** [comment]
> Try running the terminal:: CUDA_VISIBLE._DEVICES=1 python train.py --gpu-ids 0 .

Thanks，it works！
