### ISSUE TITLE
error when decompressing the pre-trained model

### ISSUE THREAD

**Issue by kkhuang1990** [jfzhang95/pytorch-deeplab-xception#137]
hi  zhang, 

thank you so much for providing the codes, after downloading the deeplab pretrained model with resnet as backbone, the downloaded .tar file cannot be decompressed. Could you please reupload the pretrained model, if so, I cannot thank you more.

**Comment by jfzhang95** [comment]
You don't have to decompress the file. Just use it as the checkpoint file.
