### ISSUE TITLE
Any trick to improve the performance? I trained my dataset on 4 GPUs

### ISSUE THREAD

**Issue by XUYUNYUN666** [jfzhang95/pytorch-deeplab-xception#138]
![image](https://user-images.githubusercontent.com/38391161/69477739-e9106a00-0e24-11ea-9ba3-22d8cc9364b1.png)

**Comment by Exception-star** [comment]
Have you trained in SBD dataset?

**Comment by XUYUNYUN666** [comment]
> Have you trained in SBD dataset?

No I just trained on my dataset

**Comment by jfzhang95** [comment]
I have updated the code, please try again.

**Comment by levi77** [comment]
I find the same problem about miou=0.5 .Have you had any solutions?
