### ISSUE TITLE
The validation result is not good.

### ISSUE THREAD

**Issue by Darcyzh** [jfzhang95/pytorch-deeplab-xception#142]
I use the default config to train on Pascal voc( no SBD), batch size is 16, epochs is 50, backbone is resnet, other configs are all default. ( I trained on 4 GPU)  And I only got about 72% of mIoU, fwIoU is 87, Acc is 92, Acc_class is 85. This result is worse than posted on https://github.com/jfzhang95/pytorch-deeplab-xception.  What is the problem?

**Comment by jfzhang95** [comment]
solved

**Comment by zhaowt61** [comment]
Could you possibly tell us how it was solved?

**Comment by MyFirst905** [comment]
I also want to know how it was solved
