### ISSUE TITLE
How to train in own dataset by pytorch-deeplab-xception

### ISSUE THREAD

**Issue by JasonChenhx** [jfzhang95/pytorch-deeplab-xception#151]
I want to ask a question,
I want to train in own dataset throught this model, but I have no idea to solve it.
Thanks!

**Comment by AndrejHafner** [comment]
You need to add/change the following things. Decide for a name of your dataset, you're going to use it in a few places and in the end pass it as an argument to *train.py*.

- *mypath.py* - Add the path to your dataset under a chosen name, the path should contain train, val and test folders. Inside them there should be images folder and annotations folder, named however you want (you will use the folder names in following changes).
- *dataloaders/utils.py* - Here add your dataset to the if sentence in *decode_segmap* function. You need to specify the number of classes and write a function that returns an numpy array of RGB values (colors) that are going to be used to define a specific classes. The number of colors must match the number of classses. Look at other functions for example.
- *dataloaders/datasets/<your_dataset>.py* - Create your own data generator. I suggest you to copy the cityscapes one and change it to the number of classes you have. In *\__init\__* you need to list all the images and annotations, change valid and void classes (your classes should always start with 0, then incremented by one). You also define class names here. Then you need change the  *\__getitem\__* function to load the image and annotation and encode it. I think the code pretty much speaks for itself here. Just change it to your case.
- *dataloaders/\_init\_.py* - Again add your dataset name here. Basically copy from other datasets, change to your own and create dataloaders.

This should be it. Try running *train.py* using the *--dataset <your_dataset_name>* flag and other necessary flags. 
Good luck!

**Comment by niqbal996** [comment]
Hi, 
I am using your code to do something similar in a plant dataset where I have three classes only ['background', 'plant', 'weed']. Here I don't want to consider the background so I set it to be something like this (correct me if am wrong): 
In dataloaders/datasets/cropweed.py
`NUM_CLASSES = 3`
`self.void_classes = [0]`
`self.valid_classes = [1, 2]`
`self.class_names = ['background', 'plants', 'weeds']`
and for  _dataloaders/utils.py_:
`def get_plant_labels():
    return np.array([
        [0, 0, 0],
        [128, 128, 128],
        [255, 255, 255]])`

I also did the rest of the changes that you mentioned. The dataloader is working fine but I think there is a problem with how my classes are organized. I get the following error: 

```Namespace(backbone='resnet', base_size=513, batch_size=4, checkname='deeplab-resnet', crop_size=513, cuda=False, dataset='cropweed', epochs=10, eval_interval=1, freeze_bn=False, ft=False, gpu_ids='0', loss_type='ce', lr=0.01, lr_scheduler='poly', momentum=0.9, nesterov=False, no_cuda=True, no_val=False, out_stride=16, resume=None, seed=1, start_epoch=0, sync_bn=False, test_batch_size=4, use_balanced_weights=False, use_sbd=True, weight_decay=0.0005, workers=4)
Found 7820 train images
Found 977 valid images
Using poly LR Scheduler!
Starting Epoch: 0
Total Epoches: 10
  0%|          | 0/1955 [00:00<?, ?it/s]
=>Epoches 0, learning rate = 0.0100,                 previous best = 0.0000
/home/robot/anaconda3/envs/pytorch-deeplab/lib/python3.6/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
  0%|          | 0/1955 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/home/robot/PycharmProjects/pytorch-deeplab-xception/train.py", line 305, in <module>
    main()
  File "/home/robot/PycharmProjects/pytorch-deeplab-xception/train.py", line 298, in main
    trainer.training(epoch)
  File "/home/robot/PycharmProjects/pytorch-deeplab-xception/train.py", line 105, in training
    loss = self.criterion(output, target)
  File "/home/robot/PycharmProjects/pytorch-deeplab-xception/utils/loss.py", line 28, in CrossEntropyLoss
    loss = criterion(logit, target.long())
  File "/home/robot/anaconda3/envs/pytorch-deeplab/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/robot/anaconda3/envs/pytorch-deeplab/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/robot/anaconda3/envs/pytorch-deeplab/lib/python3.6/site-packages/torch/nn/functional.py", line 2009, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/robot/anaconda3/envs/pytorch-deeplab/lib/python3.6/site-packages/torch/nn/functional.py", line 1840, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at /tmp/pip-req-build-ocx5vxk7/aten/src/THNN/generic/SpatialClassNLLCriterion.c:111

Process finished with exit code 1
```
My annotations are 3 channel rgb images with [0, 0, 0] as background, [128, 128, 128] as weeds, [255, 255, 255] as plants. How should I organize my classes here? I understand the problem is because of wrong class structure making the assertion fail.

**Comment by ycc66104116** [comment]
hi, i also face the same problem. did you fix it?

**Comment by chiba1sonny** [comment]
> Hi, I am using your code to do something similar in a plant dataset where I have three classes only ['background', 'plant', 'weed']. Here I don't want to consider the background so I set it to be something like this (correct me if am wrong): In dataloaders/datasets/cropweed.py `NUM_CLASSES = 3` `self.void_classes = [0]` `self.valid_classes = [1, 2]` `self.class_names = ['background', 'plants', 'weeds']` and for _dataloaders/utils.py_: `def get_plant_labels(): return np.array([ [0, 0, 0], [128, 128, 128], [255, 255, 255]])`
> 
> I also did the rest of the changes that you mentioned. The dataloader is working fine but I think there is a problem with how my classes are organized. I get the following error:
> 
> ```
> Found 7820 train images
> Found 977 valid images
> Using poly LR Scheduler!
> Starting Epoch: 0
> Total Epoches: 10
>   0%|          | 0/1955 [00:00<?, ?it/s]
> =>Epoches 0, learning rate = 0.0100,                 previous best = 0.0000
> /home/robot/anaconda3/envs/pytorch-deeplab/lib/python3.6/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
>   warnings.warn(warning.format(ret))
>   0%|          | 0/1955 [00:05<?, ?it/s]
> Traceback (most recent call last):
>   File "/home/robot/PycharmProjects/pytorch-deeplab-xception/train.py", line 305, in <module>
>     main()
>   File "/home/robot/PycharmProjects/pytorch-deeplab-xception/train.py", line 298, in main
>     trainer.training(epoch)
>   File "/home/robot/PycharmProjects/pytorch-deeplab-xception/train.py", line 105, in training
>     loss = self.criterion(output, target)
>   File "/home/robot/PycharmProjects/pytorch-deeplab-xception/utils/loss.py", line 28, in CrossEntropyLoss
>     loss = criterion(logit, target.long())
>   File "/home/robot/anaconda3/envs/pytorch-deeplab/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/robot/anaconda3/envs/pytorch-deeplab/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 916, in forward
>     ignore_index=self.ignore_index, reduction=self.reduction)
>   File "/home/robot/anaconda3/envs/pytorch-deeplab/lib/python3.6/site-packages/torch/nn/functional.py", line 2009, in cross_entropy
>     return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
>   File "/home/robot/anaconda3/envs/pytorch-deeplab/lib/python3.6/site-packages/torch/nn/functional.py", line 1840, in nll_loss
>     ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
> RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at /tmp/pip-req-build-ocx5vxk7/aten/src/THNN/generic/SpatialClassNLLCriterion.c:111
> 
> Process finished with exit code 1
> ```
> 
> My annotations are 3 channel rgb images with [0, 0, 0] as background, [128, 128, 128] as weeds, [255, 255, 255] as plants. How should I organize my classes here? I understand the problem is because of wrong class structure making the assertion fail.

Hey, I have the same problem. Did you fix it?

**Comment by wangnanv5** [comment]
# make one-hot can solve this problem,

def mask_to_onehot(mask, palette):
    """
    Converts a segmentation mask (H, W, C) to (H, W, K) where the last dim is a one
    hot encoding vector, C is usually 1 or 3, and K is the number of class.
    """
    semantic_map = []
    for colour in palette:
        equality = np.equal(mask, colour)
        class_map = np.all(equality, axis=-1)
        semantic_map.append(class_map)
    semantic_map = np.stack(semantic_map, axis=-1).astype(np.float32)
    return semantic_map

def onehot_to_mask(mask, palette):
    """
    Converts a mask (H, W, K) to (H, W, C)
    """
    x = np.argmax(mask, axis=-1)
    colour_codes = np.array(palette)
    x = np.uint8(colour_codes[x.astype(np.uint8)])
    return x

palette = [[0], [128], [255]]  
gt_onehot = mask_to_onehot(gt, palette)
#  gt->shape  [H, W, x]，  make sure x is your classes number
