### ISSUE TITLE
how to label my own picture

### ISSUE THREAD

**Issue by huidemie** [jfzhang95/pytorch-deeplab-xception#152]
Thank you for your coding. I want to use my own data to  train the model. So when I label my picture, I  just need to label them like "xxxxgtFine_labelIds.png " .Other file such as ".json"  and other ".png" file is not needed, right?

**Comment by kungkook** [comment]
I also want to use this model to train my data set. Do you know how to do that

**Comment by huidemie** [comment]
> I also want to use this model to train my data set. Do you know how to do that

you can use "labelme" as tool to label your own image. I try it successfully.
