### ISSUE TITLE
IndexError when training my own VOC dataset

### ISSUE THREAD

**Issue by ghost** [jfzhang95/pytorch-deeplab-xception#162]
After I added my own dataset into the code, when training, it will raise questions like this:

  File "F:\pytorch-deeplab-xception-master\loss.py", line 28, in CrossEntropyLoss
    loss = criterion(logit, target.long())

  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)

  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)

  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 2021, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)

  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 1840, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

**IndexError: Target 5 is out of bounds.**

My num_classes is 4.

**Comment by kungkook** [comment]
How do you make your own voc data set

**Comment by ghost** [comment]
I use labelme and then use label2voc to transform.


On 04/20/2020 11:19, kungkook wrote:

How do you make your own voc data set

**Comment by kungkook** [comment]
> I use labelme and then use label2voc to transform. On 04/20/2020 11:19, kungkook wrote: How do you make your own voc data set — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Is it convenient to share label2voc code

**Comment by elenazyl98326** [comment]
See in attachment~
On 4/20/2020 11:19，kungkook<notifications@github.com> wrote：

How do you make your own voc data set

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 10 14:14:17 2020

@author: 张雅翎
"""
from __future__ import print_function
 
import argparse
import glob
import json
import os
import os.path as osp
import sys
 
import numpy as np
import PIL.Image
 
import labelme
from sklearn.model_selection import train_test_split
 
 
def main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument('input_dir', help='input annotated directory')
    parser.add_argument('output_dir', help='output dataset directory')
    parser.add_argument('--labels', help='labels file', required=True)
    args = parser.parse_args()
 
 
    if osp.exists(args.output_dir):
        print('Output directory already exists:', args.output_dir)
#        sys.exit(1)
    else:
        os.makedirs(args.output_dir)
        os.makedirs(osp.join(args.output_dir, 'JPEGImages'))
        os.makedirs(osp.join(args.output_dir, 'SegmentationClass'))
    #    os.makedirs(osp.join(args.output_dir, 'SegmentationClassPNG'))
        os.makedirs(osp.join(args.output_dir, 'SegmentationClassVisualization'))
    saved_path = args.output_dir
    if not os.path.exists(os.path.join(saved_path , 'ImageSets','Segmentation')):
        os.makedirs(os.path.join(saved_path , 'ImageSets','Segmentation'))
    print('Creating dataset:', args.output_dir)
 
    class_names = []
    class_name_to_id = {}
    for i, line in enumerate(open(args.labels).readlines()):
        print(i)
        class_id = i+1 # starts with -1
        class_name = line.strip()
        class_name_to_id[class_name] = class_id
        if class_id == -1:
            assert class_name == '__ignore__'
            continue
        elif class_id == 0:
            assert class_name == '_background_'
        class_names.append(class_name)
    class_names = tuple(class_names)
    print('class_names:', class_names)
    out_class_names_file = osp.join(args.output_dir, 'class_names.txt')
    with open(out_class_names_file, 'w') as f:
        f.writelines('\n'.join(class_names))
    print('Saved class_names:', out_class_names_file)
 
    colormap = labelme.utils.label_colormap(255)
 
    for label_file in glob.glob(osp.join(args.input_dir, '*.json')):
        print('Generating dataset from:', label_file)
        try:
            with open(label_file) as f:
                base = osp.splitext(osp.basename(label_file))[0]
                out_img_file = osp.join(
                    args.output_dir, 'JPEGImages', base + '.jpg')
    #            out_lbl_file = osp.join(
    #                args.output_dir, 'SegmentationClass', base + '.npy')
    #                args.output_dir, 'SegmentationClass', base + '.npy')
                out_png_file = osp.join(
                    args.output_dir, 'SegmentationClass', base + '.png')
                out_viz_file = osp.join(
                    args.output_dir,
                    'SegmentationClassVisualization',
                    base + '.jpg',
                )
    
                data = json.load(f)
    
                img_file = osp.join(label_file.split('.json')[0]+'.jpg')
                img = np.asarray(PIL.Image.open(img_file))
                PIL.Image.fromarray(img).save(out_img_file)
    
    
                print('class_name_to_id:',class_name_to_id)
                lbl = labelme.utils.shapes_to_label(
                    img_shape=img.shape,
                    shapes=data['shapes'],
                    label_name_to_value=class_name_to_id,
                )
                labelme.utils.lblsave(out_png_file, lbl)
    
    #            np.save(out_lbl_file, lbl)
    
                viz = labelme.utils.draw_label(
                    lbl, img, class_names, colormap=colormap)
                PIL.Image.fromarray(viz).save(out_viz_file)
        except:
            with open('wrongdata.txt','w') as f:
                f.write(label_file+'\n')
            print('这张图像有错误')
            continue
            
    #6.split files for txt
    txtsavepath = os.path.join(saved_path , 'ImageSets','Segmentation')
    ftrainval = open(os.path.join(txtsavepath,'trainval.txt'), 'w')
    ftest = open(os.path.join(txtsavepath,'test.txt'), 'w')
    ftrain = open(os.path.join(txtsavepath,'train.txt'), 'w')
    fval = open(os.path.join(txtsavepath,'val.txt'), 'w')
    total_files = os.listdir(osp.join(args.output_dir, 'SegmentationClass'))
    total_files = [i.split("/")[-1].split(".png")[0] for i in total_files]
    #test_filepath = ""
    for file in total_files:
        ftrainval.write(file + "\n")
    #test
    #for file in os.listdir(test_filepath):
    #    ftest.write(file.split(".jpg")[0] + "\n")
    #split
    train_files,val_files = train_test_split(total_files,test_size=0.15,random_state=42)
    #train
    for file in train_files:
        ftrain.write(file + "\n")
    #val
    for file in val_files:
        fval.write(file + "\n")
    
    ftrainval.close()
    ftrain.close()
    fval.close()
    ftest.close()
 
 
 
if __name__ == '__main__':
    main()

**Comment by kungkook** [comment]
thank you，May I know how you installed the pre-training environment? I always make assertions wrong

**Comment by ghost** [comment]
Using anaconda.


On 04/20/2020 14:15, kungkook wrote:

thank you，May I know how you installed the pre-training environment? I always make assertions wrong
