### ISSUE TITLE
using your codes train the voc datasets from scratch got very large loss value?

### ISSUE THREAD

**Issue by monk42** [jfzhang95/pytorch-deeplab-xception#27]
Sorry to bother u, I find no error in your source code, but I can't understand why i got very large loss vale.
can you give any  guidance to me to fix my problem. thanks!

![image](https://user-images.githubusercontent.com/33028017/48902365-56e12900-ee93-11e8-92b1-ed844e5f459c.png)

**Comment by jfzhang95** [comment]
Please look at #20

**Comment by monk42** [comment]
Thanks! I will try this method next!
