### ISSUE TITLE
Performance on Cityscape

### ISSUE THREAD

**Issue by lxtGH** [jfzhang95/pytorch-deeplab-xception#29]
Hi ! What is the final Performance on Cityscape dataset???

**Comment by lxtGH** [comment]
OK~ I will have a try~ 73%mIOU is not correct. because single resnet101 can achieve that point.

**Comment by jfzhang95** [comment]
Good luck and I will also explore the performance gap later.

**Comment by yazhe2017** [comment]
Hi, thanks for the great repo. I try to train the cityscapes dataset with the suggested parameters. However, the performance of network is weird. The epoch loss decrease all the way. However, it is weird to note that the miou first rise then descend and the highest miou is 57.5%. Could you please try to give a suggestion on this? Thanks a lot.
My parameters setting is 4 v100 GPUs, bs=16, base_size=513, crop_size=513, backbone=resnet lr=0.01. I made additional trying with setting as 8 v100 GPUs, base_size=1024, crop_size=769. However, the performances for both experiments are similar.

![loss](https://user-images.githubusercontent.com/34027393/52681318-66de4580-2f76-11e9-820c-e4549f924487.png)

![miou](https://user-images.githubusercontent.com/34027393/52681334-75c4f800-2f76-11e9-9b78-28fd27ef6859.png)

**Comment by HuayueZhang** [comment]
> Hi, thanks for the great repo. I try to train the cityscapes dataset with the suggested parameters. However, the performance of network is weird. The epoch loss decrease all the way. However, it is weird to note that the miou first rise then descend and the highest miou is 57.5%. Could you please try to give a suggestion on this? Thanks a lot.
> My parameters setting is 4 v100 GPUs, bs=16, base_size=513, crop_size=513, backbone=resnet lr=0.01. I made additional trying with setting as 8 v100 GPUs, base_size=1024, crop_size=769. However, the performances for both experiments are similar.
> 
> ![loss](https://user-images.githubusercontent.com/34027393/52681318-66de4580-2f76-11e9-820c-e4549f924487.png)
> 
> ![miou](https://user-images.githubusercontent.com/34027393/52681334-75c4f800-2f76-11e9-9b78-28fd27ef6859.png)

Hello~ I got the same curve with you. Have you resoloved this question?
