### ISSUE TITLE
Is there any problem with exit flow of Xception?

### ISSUE THREAD

**Issue by Woolseyyy** [jfzhang95/pytorch-deeplab-xception#3]
The output size is 256x256 in the example code, in which input's size is 512x512.

I find that there are some differences with official tensorflow version. That version uses dilated convolution(rate 2, stride 1) in exit flow and uses stride 1 convolution in skip connection. 

As a result, in their version, the scale rate of Xception layer is 16 instead of 32. The whole model can produce same size output with input instead half of input.

Do I mistake something?

**Comment by jfzhang95** [comment]
I read the official tensorflow implemented deeplab and I think you are right. 
I really misunderstand some parts of the Exitflow module.

Currently, I implement a new separable convolution function to solve this problem.
The output_stride is 16 instead of 32 now.

Thank you for correcting me!
