### ISSUE TITLE
Why DW is not followed by BN in Xception?

### ISSUE THREAD

**Issue by lionel3** [jfzhang95/pytorch-deeplab-xception#34]
I have some questions about the network architecture.
1. Why no BN after DW in Xception-backbone
2. In Resnet Backbone, when os=8, the dilation rate of convs in block3 should all be 2, but you only make the rate of the first conv layer to be 2.
3. For os=16, when Resnet has only 4 blocks, blocks[1,2,4] is a better choice. But I don't think blocks[1, 2, 1] for os=8 is a right choice.
4. Maybe we should add more choice for Resnet structure, for example, 7 blocks just as proposed in paper of DeepLabv3.

**Comment by jfzhang95** [comment]
Hi, lionel3

For 1 and 2: you're right. It seems like my negligence.
For 3: when output_stride=8, dilation should be bigger. I checked origin tf code, it set blocks = [1, 2,  4] for both os=16 and os=8. Therefore, when os=8, the final dilation in layer 4 is 4, 8, 16.
For 4: I will add more backbone setting when I have free time.

**Comment by lionel3** [comment]
Thanks for your quick reply. It actually solves my confusion.

**Comment by jfzhang95** [comment]
You are welcome.
