### ISSUE TITLE
Questions about the experiment on Cityscapes dataset

### ISSUE THREAD

**Issue by jfzhuang** [jfzhang95/pytorch-deeplab-xception#4]
Hello, thanks for offering your implementation about Deeplabv3+ on Pytorch. However, when I utilize your code to conduct a experiment on the Cityscapes dataset, I can not obtain a comparable result with the results published in the paper. My result on the val subset is about 36% on mIoU, which is much lower than the published result (greater than 75%). All training configurations I used are according to the paper (Deeplabv3+ and Deeplabv3). Have you conducted similar experiments on the Cityscapes dataset? Or can you provide any suggestion? Thanks a lot!

**Comment by jfzhang95** [comment]
Sorry, currently I only train this model in Pascal Voc 2012. My suggestions are as follows

1) Previous implemented deeplab v3+ has some errors, you can check whether 
the model output_stride is 16. If it's not, you can replace the old model with 
new implemented model.

2) Current deeplab v3+ pretrain weights are load from xception. But I think it is 
not the most suitable way to load pretrain model. You can try some other ways 
to load pretrain model. 

3) You can apply data augmentation to prevent overfit.

**Comment by jfzhuang** [comment]
Thanks for your reply and suggestions! And I wonder if you reproduce the experimental result on the Pascal VOC dataset as published in the paper?

**Comment by jfzhang95** [comment]
Currently not. This program is still in progress. If I reproduce the results,
I will update it in this repo~
