### ISSUE TITLE
a simple problem: why input size 513*513

### ISSUE THREAD

**Issue by zxshi** [jfzhang95/pytorch-deeplab-xception#40]
I don't konw why input size is 513*513, my image size is 512*512, your previous code is 512*512. 
Can you teach me the reason?

**Comment by jfzhang95** [comment]
Hi, because the official paper and TF code input size is 513.

**Comment by zxshi** [comment]
yes, I notice it. But I don't know why do it.
512*512 also works fine in your last version of the code.

**Comment by jfzhang95** [comment]
You can see Q8 in [FAQ](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/faq.md).

**Comment by zxshi** [comment]
I got the answer from [here](https://github.com/tensorflow/models/issues/3886).

**Comment by zxshi** [comment]
Thank you for your reply.
