### ISSUE TITLE
Models are not in tar format

### ISSUE THREAD

**Issue by lutzroeder** [jfzhang95/pytorch-deeplab-xception#42]
The models linked via `README.md` have a `.tar` file extension but are not in `.tar` format.

For example `deeplab-resnet.pth.tar` starts with `0x80 0x02` and is a PyTorch `.pth` pickle file, not a tar file.

**Comment by SonyPony** [comment]
So, you just removed .tar extension?

**Comment by lutzroeder** [comment]
Yes
