### ISSUE TITLE
Single GPU

### ISSUE THREAD

**Issue by yyangmei** [jfzhang95/pytorch-deeplab-xception#44]
Hello, I want to use single gpu to train the net. But I find that if I choose to use gpu-ids=1 or 2, the following error will appear。
![image](https://user-images.githubusercontent.com/42143920/49911510-a67aa980-fec1-11e8-9204-daa24d619e51.png)
Fortunately， if I choose gpu-ids=0 the code will work successful. 
But why? Can I use single gpu with other gpu-ids not 0?

**Comment by jfzhang95** [comment]
Hi,

You can set ``CUDA_VISIBLE_DEVICES=x``, x is the gpu id you want to use. Also you should set ``--gpu-ids 0`` when using single gpu.

**Comment by yyangmei** [comment]
@jfzhang95  Thank you so much!
What's more, if I want to use two gpus can I choose any two different ids such as 1,2 or 1,3?
At that time how should I set the --gpu-ids?

**Comment by jfzhang95** [comment]
If you use gpu 2 and 3, you should run:

``CUDA_VISIBLE_DEVICES=2,3 python train.py --backbone resnet --lr 0.007 --workers 4 --epochs 50 --batch-size 8 --gpu-ids 0,1 --dataset pascal``

**Comment by stonessss** [comment]
hello!
I have two GPUs on my device. I want to use them separately. When I use GPU1, I find that the memory is not occupied, and the utilization rate is very low. Are they all running on GPU0?
If i want use GPU1 separately,How do I set it ?
