### ISSUE TITLE
pretrained model is error，failed to decompression

### ISSUE THREAD

**Issue by ChaosCen** [jfzhang95/pytorch-deeplab-xception#75]
![捕获](https://user-images.githubusercontent.com/10510830/55057949-a0da5580-50a5-11e9-827d-0c2646761c98.PNG)

**Comment by duwangzhe** [comment]
The same question happens to me

**Comment by jfzhang95** [comment]
Hi, you don't need to decompress it. Please see in [here](https://github.com/jfzhang95/pytorch-deeplab-xception/blob/c8ff02c6eeb2b774ad5a25557a60ee48e04635c6/train.py#L74) for how to load pertained model. `args.resume` could be set to `'deeplab-resnet.pth.tar'` in your case.

**Comment by ChaosCen** [comment]
OK, Thank you for reply.
