### ISSUE TITLE
'DeepLab' object has no attribute 'module'

### ISSUE THREAD

**Issue by abhimanyuchadha96** [jfzhang95/pytorch-deeplab-xception#80]
I simply tried running 'python train.py' with all arguments as default and after one epoch it gives an error 

Traceback (most recent call last):
File "train.py", line 303, in <module>
main()
File "train.py", line 298, in main
trainer.validation(epoch)
File "train.py", line 173, in validation
'state_dict': self.model.module.state_dict(),
File "~/torch/nn/modules/module.py", line 535, in __getattr__
type(self).__name__, name))
AttributeError: 'DeepLab' object has no attribute 'module'

**Comment by duwangzhe** [comment]
hi I meet the same question, could you provide the solution to the issue? Thanks a lot!

**Comment by abhimanyuchadha96** [comment]
Downgrade the version of your PyTorch to the one mentioned in the repository.

**Comment by duwangzhe** [comment]
Thanks for replying me. I have checked the version of the PyTorch, it is 0.4.1, just be the same in the repository

**Comment by abhimanyuchadha96** [comment]
This solved my error. I can't say why it isn't solving yours.
Maybe you could check if you're running it on CUDA or not. Verify the CUDA version too. 

If you're using anaconda, just create a new environment.

**Comment by chyohoo** [comment]
Have you solved this?

**Comment by andrew-begain** [comment]
@duwangzhe hi，have you solved this problem?thanks

**Comment by lromor** [comment]
Same problem

**Comment by andrew-begain** [comment]
> Same problem
change 'state_dict': self.model.module.state_dict() to 'state_dict': self.model.state_dict()
it work for me

**Comment by xiazhenyz** [comment]
> > Same problem
> > change 'state_dict': self.model.module.state_dict() to 'state_dict': self.model.state_dict()
> > it work for me

Thanks， it work for me too
