### ISSUE TITLE
About data transform

### ISSUE THREAD

**Issue by MenghaoGuo** [jfzhang95/pytorch-deeplab-xception#82]
Thanks for your code, it helps me a lot.
I'm confused about the custom_transform. I don't know why you rescale images by Image.BILINEAR  but rescale mask by Image.NEAREST.

**Comment by theevann** [comment]
Image.NEAREST will find the closest point in the original image and use its value.
We don't want an interpolation (such as what does Image.BILINEAR) because it would give a floating number, and this would make no sense since the values in the mask are integers and represents the class.

**Comment by MenghaoGuo** [comment]
Thanks for your reply. Can I use Image.NEAREST in the original image ?

**Comment by theevann** [comment]
Yes, but bilinear is visually better. This change may affect the network perfomance.

**Comment by MenghaoGuo** [comment]
Thanks.
