### ISSUE TITLE
Data corruption on provided pretrained model

### ISSUE THREAD

**Issue by linkAmy** [jfzhang95/pytorch-deeplab-xception#87]
@jfzhang95 Thanks very much for providing pretrained models on google drive. But I got **Data corruption** when I try to unpack deeplab-resnet.pth.tar using unachriver. I also tried to use tar directly in commend line but still failed. 
Is there something wrong with the data or it just happens to me?
Looking forward to your reply.

**Comment by theevann** [comment]
It is not a tar file, so you should just rename `deeplab-resnet.pth.tar` as `deeplab-resnet.pth`

**Comment by linkAmy** [comment]
oh, thanks very much
