### ISSUE TITLE
Error in training COCO 

### ISSUE THREAD

**Issue by George1ee** [jfzhang95/pytorch-deeplab-xception#90]
Thanks for your code. But I am confused about why I can't find the picture since index is already created and the annotations are loaded. 

![image](https://user-images.githubusercontent.com/13507259/58064404-83f96480-7bb4-11e9-9a6c-cdcfec1d4d96.png)

**Comment by guvcolie** [comment]
@George1ee Hi, I met the same problem, how do you solve it?

**Comment by JiihwanKim** [comment]
Add the line below to the `_preprocess` function.
```cocotarget = self.coco.loadAnns(self.coco.getAnnIds(imgIds=img_id))
img_metadata = self.coco.loadImgs(img_id)[0]
if not os.path.exists(os.path.join(self.img_dir, img_metadata['file_name'])):
    continue
```
This code will create a segmentation mask only if the image exists.
