### ISSUE TITLE
Bad result with provided model, "deeplab-resnet.pth"

### ISSUE THREAD

**Issue by PTL2011** [jfzhang95/pytorch-deeplab-xception#97]
Using the provided model deeplab-resnet.pth from google drive, I got the following result.
![image](https://user-images.githubusercontent.com/38207414/59897636-20b35a00-9420-11e9-95c6-a8d2748f60d1.png)

Test loss: 3.045851: 100%|██████████████████████████████████████████████████████████████████████| 363/363 [03:42<00:00,  2.06it/s]
Validation:
[numImages:  1449]
Acc:0.017332007782534742, Acc_class:0.0529151632597871, mIoU:0.002817205803557816, fwIoU: 0.0011586984138953578
Loss: 1105.644
I think this shouldn't be the expected result, can anybody tell me what's wrong?

**Comment by jfzhang95** [comment]
Try new code please.
